name: API Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Postman Collection
        uses: postmanlabs/postman-cli-action@v1
        with:
          command: 'collection run 7457366-6ac1de03-b3e6-4c8b-86f2-1c0c662cb8c4'
          api-key: ${{ secrets.POSTMAN_API_KEY }}
